=== gusnrl/mule-cicd-sample/.mule/plugins-tmp/mule-rosettanet-connector-2.0.0-mule-plugin/schemas/pip-detail.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--

    (c) 2003-2017 MuleSoft, Inc. This software is protected under international copyright law. All use of this software
    is subject to MuleSoft's Master Subscription Agreement (or other Terms of Service) separately entered into between
    you and MuleSoft. If such an agreement is not in place, you may not use the software.

-->
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
 <xsd:element name="pip" type="pipDetail"/>
 <xsd:complexType name="pipDetail">
  <xsd:sequence>
   <xsd:element name="processCode" type="xsd:string"/>
   <xsd:element name="transactionCode" type="xsd:string"/>
   <xsd:element name="activityIdentifier" type="xsd:string"/>
   <xsd:element name="initiatorPartnerRole" type="xsd:string"/>
   <xsd:element name="initiatorServiceCode" type="xsd:string"/>
   <xsd:element name="responderPartnerRole" type="xsd:string"/>
   <xsd:element name="responderServiceCode" type="xsd:string"/>
   <xsd:element name="requireSync" type="xsd:boolean"/>
   <xsd:element name="requireAsync" type="xsd:boolean"/>
   <xsd:element name="retryCount" type="xsd:int"/>
   <xsd:element name="initiatorAction" type="actionDetail"/>
   <xsd:element name="responderAction" type="actionDetail" minOccurs="0"/>
  </xsd:sequence>
  <xsd:attribute name="pipCode" type="xsd:string"  use="required"/>
  <xsd:attribute name="pipVersion" type="xsd:string"  use="required"/>
 </xsd:complexType>
 <xsd:complexType name="actionDetail">
  <xsd:sequence>
   <xsd:element name="actionCode" type="xsd:string"/>
   <xsd:element name="requireSignedAction" type="xsd:boolean"/>
   <xsd:element name="requireSignedAcknowledge" type="xsd:boolean"/>
   <xsd:element name="timeToAcknowledge" type="xsd:int"/>
   <xsd:element name="dtdName" type="xsd:string"/>
   <xsd:element name="xsdName" type="xsd:string"/>
  </xsd:sequence>
 </xsd:complexType>
</xsd:schema>

=== gusnrl/mule-cicd-sample/.mule/plugins-tmp/mule-rosettanet-connector-2.0.0-mule-plugin/PIP3A6/V02_02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    (c) 2003-2017 MuleSoft, Inc. This software is protected under international copyright law. All use of this software
    is subject to MuleSoft's Master Subscription Agreement (or other Terms of Service) separately entered into between
    you and MuleSoft. If such an agreement is not in place, you may not use the software.

-->
<pip pipCode="3A6" pipVersion="V02.02"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schemas/pip-detail.xsd">
  <processCode>Distribute Order Status</processCode>
  <transactionCode>Distribute Order Status</transactionCode>
  <activityIdentifier>Distribute Purchase Order Status</activityIdentifier>
  <initiatorPartnerRole>Seller</initiatorPartnerRole>
  <initiatorServiceCode>Seller Service</initiatorServiceCode>
  <responderPartnerRole>Buyer</responderPartnerRole>
  <responderServiceCode>Buyer Service</responderServiceCode>
  <requireSync>false</requireSync>
  <requireAsync>true</requireAsync>
  <retryCount>3</retryCount>
  <initiatorAction>
    <actionCode>Purchase Order Status Notification Action</actionCode>
    <requireSignedAction>false</requireSignedAction>
    <requireSignedAcknowledge>false</requireSignedAcknowledge>
    <timeToAcknowledge>7200</timeToAcknowledge>
    <dtdName>3A6_MS_V02_02_PurchaseOrderStatusNotification.dtd</dtdName>
    <xsdName>3A6_MS_V02_02_PurchaseOrderStatusNotification.xsd</xsdName>
  </initiatorAction>
</pip>

=== gusnrl/mule-cicd-sample/.mule/plugins-tmp/mule-rosettanet-connector-2.0.0-mule-plugin/PIP0A1/V02_00.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    (c) 2003-2017 MuleSoft, Inc. This software is protected under international copyright law. All use of this software
    is subject to MuleSoft's Master Subscription Agreement (or other Terms of Service) separately entered into between
    you and MuleSoft. If such an agreement is not in place, you may not use the software.

-->
<pip pipCode="0A1" pipVersion="V02.00"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schemas/pip-detail.xsd">
  <processCode>Failure Notification</processCode>
  <transactionCode>Failure Notification</transactionCode>
  <activityIdentifier>Distribute Notification of Failure</activityIdentifier>
  <initiatorPartnerRole>P I P Failure Notifier</initiatorPartnerRole>
  <initiatorServiceCode>P I P Failure Notifier Service</initiatorServiceCode>
  <responderPartnerRole>Failure Report Administrator</responderPartnerRole>
  <responderServiceCode>Failure Report Administrator Service</responderServiceCode>
  <requireSync>false</requireSync>
  <requireAsync>true</requireAsync>
  <retryCount>3</retryCount>
  <initiatorAction>
    <actionCode>Failure Notification Action</actionCode>
    <requireSignedAction>false</requireSignedAction>
    <requireSignedAcknowledge>false</requireSignedAcknowledge>
    <timeToAcknowledge>7200</timeToAcknowledge>
    <dtdName>0A1_MS_V02_00_FailureNotification.dtd</dtdName>
    <xsdName>0A1_MS_V02_00_FailureNotification.xsd</xsdName>
  </initiatorAction>
</pip>

=== gusnrl/mule-cicd-sample/.mule/plugins-tmp/mule-rosettanet-connector-2.0.0-mule-plugin/PIP3B2/V01_00.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    (c) 2003-2017 MuleSoft, Inc. This software is protected under international copyright law. All use of this software
    is subject to MuleSoft's Master Subscription Agreement (or other Terms of Service) separately entered into between
    you and MuleSoft. If such an agreement is not in place, you may not use the software.

-->
<pip pipCode="3B2" pipVersion="V01.00"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schemas/pip-detail.xsd">
  <processCode>Notify of Advance Shipment</processCode>
  <transactionCode>Notify of Advance Shipment</transactionCode>
  <activityIdentifier>Notify of Advance Shipment</activityIdentifier>
  <initiatorPartnerRole>Shipper</initiatorPartnerRole>
  <initiatorServiceCode>Shipper Service</initiatorServiceCode>
  <responderPartnerRole>Receiver</responderPartnerRole>
  <responderServiceCode>Receiver Service</responderServiceCode>
  <requireSync>false</requireSync>
  <requireAsync>true</requireAsync>
  <retryCount>3</retryCount>
  <initiatorAction>
    <actionCode>Advance Shipment Notification Action</actionCode>
    <requireSignedAction>true</requireSignedAction>
    <requireSignedAcknowledge>true</requireSignedAcknowledge>
    <timeToAcknowledge>1800</timeToAcknowledge>
    <dtdName>3B2_MS_V01_00_AdvanceShipmentNotification.dtd</dtdName>
    <xsdName>3B2_MS_V01_00_AdvanceShipmentNotification.xsd</xsdName>
  </initiatorAction>
</pip>

=== gusnrl/mule-cicd-sample/.mule/plugins-tmp/mule-rosettanet-connector-2.0.0-mule-plugin/PIP3C3/V01_01.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    (c) 2003-2017 MuleSoft, Inc. This software is protected under international copyright law. All use of this software
    is subject to MuleSoft's Master Subscription Agreement (or other Terms of Service) separately entered into between
    you and MuleSoft. If such an agreement is not in place, you may not use the software.

-->
<pip pipCode="3C3" pipVersion="V01.01"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schemas/pip-detail.xsd">
  <processCode>Notify of Invoice</processCode>
  <transactionCode>Notify of Invoice</transactionCode>
  <activityIdentifier>Notify of Invoice</activityIdentifier>
  <initiatorPartnerRole>Invoice Provider</initiatorPartnerRole>
  <initiatorServiceCode>Invoice Provider Service</initiatorServiceCode>
  <responderPartnerRole>Invoice Receiver</responderPartnerRole>
  <responderServiceCode>Invoice Receiver Service</responderServiceCode>
  <requireSync>false</requireSync>
  <requireAsync>true</requireAsync>
  <retryCount>3</retryCount>
  <initiatorAction>
    <actionCode>Invoice Notification Action</actionCode>
    <requireSignedAction>true</requireSignedAction>
    <requireSignedAcknowledge>true</requireSignedAcknowledge>
    <timeToAcknowledge>7200</timeToAcknowledge>
    <dtdName>3C3_MS_V01_01_InvoiceNotification.dtd</dtdName>
    <xsdName>3C3_MS_V01_01_InvoiceNotification.xsd</xsdName>
  </initiatorAction>
</pip>

=== gusnrl/mule-cicd-sample/.mule/plugins-tmp/mule-rosettanet-connector-2.0.0-mule-plugin/PIP3A4/V02_02.xml
<?xml version="1.0" encoding="UTF-8"?>
<!--

    (c) 2003-2017 MuleSoft, Inc. This software is protected under international copyright law. All use of this software
    is subject to MuleSoft's Master Subscription Agreement (or other Terms of Service) separately entered into between
    you and MuleSoft. If such an agreement is not in place, you may not use the software.

-->
<pip pipCode="3A4" pipVersion="V02.02"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xsi:noNamespaceSchemaLocation="../schemas/pip-detail.xsd">
  <processCode>Request Purchase order</processCode>
  <transactionCode>Request Purchase Order</transactionCode>
  <activityIdentifier>Request Purchase Order</activityIdentifier>
  <initiatorPartnerRole>Buyer</initiatorPartnerRole>
  <initiatorServiceCode>Buyer Service</initiatorServiceCode>
  <responderPartnerRole>Seller</responderPartnerRole>
  <responderServiceCode>Seller Service</responderServiceCode>
  <requireSync>false</requireSync>
  <requireAsync>true</requireAsync>
  <retryCount>3</retryCount>
  <initiatorAction>
    <actionCode>Purchase Order Request Action</actionCode>
    <requireSignedAction>true</requireSignedAction>
    <requireSignedAcknowledge>true</requireSignedAcknowledge>
    <timeToAcknowledge>7200</timeToAcknowledge>
    <dtdName>3A4_MS_V02_02_PurchaseOrderRequest.dtd</dtdName>
    <xsdName>3A4_MS_V02_02_PurchaseOrderRequest.xsd</xsdName>
  </initiatorAction>
  <responderAction>
    <actionCode>Purchase Order Confirmation Action</actionCode>
    <requireSignedAction>true</requireSignedAction>
    <requireSignedAcknowledge>true</requireSignedAcknowledge>
    <timeToAcknowledge>7200</timeToAcknowledge>
    <dtdName>3A4_MS_V02_02_PurchaseOrderConfirmation.dtd</dtdName>
    <xsdName>3A4_MS_V02_02_PurchaseOrderConfirmation.xsd</xsdName>
  </responderAction>
</pip>
